language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

deploy:
  provider: firebase
  token:
    secure: "pCCm1hV1bjzYOPZWRMnA5NAPcyu/uq9GnUhR5GwaS49ENcmRqQxhGQza65RvT/3/im9D1pIeqaX0Ed5AlJvL5qYkek2NSCIr8LzDR13pdqaxzeCCFctayT56KoqHyHKrBC719JPqsnGNRQbE4M612R7KNwdanNQuZhis12DkGDpCnSpTcJBzu7YMerQj9pJ89hSm4tSzcU1uzuLMtmwaAuHfz2QUu28J9xUc2UuNQhfw1+fKy4gZBvvKzg/m2f8/2yRzXts3XZVvBYrvwAnIh6ZjfQgk9oeGrHHrZTgtgTF1RNXYNc9gnado97k+xDzrd/tQ5NciQtUI4pbxTftyVxq73DonQwKL0eBkK2+vGbLB7xx6nbP5/KeGN00QiWvxrxLccZ6Fu+yfkdVhqelRqSA8KP499QN1fTslRRqrVp6uk+sxUgFaov9A4eQEvsVtlxsXRP5iOnV2a1XXK1L6axzFHFIpys5LdFr3lyeAlBOAXf4UMX465LK1vamh8lJ/1+ArZTb/ONk7+df5T9RJ6hCMq9AcNCUA3cV0yGG56TJc5tsVM2Jp8hL8/mKJRNxRuy7nbzJ2DVYj+eYiYfGuYxRnSOzXZBGy94pVZQPIglHIYAni+VV91mfDyRXVRownMkpG5irgoxAxPP60PYuSDi9s4IO41XFLtXpwHdTGHVk="
  project:
    secure: "E5pODGlDdzqZifLfh9yCv5VF3SNpq18TfalnghElMNZpuHPt/UzUMTWXx24q5qD9fgM41OHNQO6KUtFgvOVNB3KIcvnrgIGolTGSZzHaOAkHtRXmEK5QlPC8WTKFYI+9GzA8+d3dpww3yQL/qwGy5ViSfA0s5mVXpn+xXlLa7pUuijI1Xxh/OZIOmtAIAalKUXXZc2C4WOG2AbuRiFPkyOTbuy21CDL2uU27XMRcfzZyx4w7nzKz3X2/mhK4UdAOub7Foyx6NnfNsyT6C/z6++hGNCQVnL/xFlpsM8Ysg6W1leXszGby+vSkk0cPgevNVS1dGBtQB0kJXKNkM5rViE6jZCbi00UHEGCbj6HX0UjHQ4ppgbhglqhoLB/9BGuEg1R6H0mDugMZwsGhMn7bAZv784nNp5IQwiCjXLlOBPSJOSe6lJ1DwjLvl/RgY5O1bZGqNiYt8wXKOVt1gHDsnwkf2b0/oIebQkgAq0f9Ad1C0b0H7dcAHAk30FqZsKUnn+5yg8iZbwQadhzXoEI2aa9fdkjgov/hvjQQfmfYOTA4p4QgKr3LS2lyTD6Cl8VGQGzHWFgNIWduvF1dyRD33grQZ659kJuklhsIs82AdYtQRrmG0ljMUyJ9eEUMqfDLQ5mzmdGs0hnvLXwTnAl75fpyXgwaA5sjO1fsAB3fZ0M="
  message: "Travis CI deployment"

script:
  - jshint public

after_deploy:
  - ./delete-changed-files.sh