language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project ${FIREBASE_PROJECT}