language: node_js
node_js:
  - "6.2.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project ${FIREBASE_PROJECT} --only hosting --non-interactive

after_success:
  - curl https://www.cloudflare.com/api_json.html -d 'a=fpurge_ts' -d 'tkn=${CLOUDFLARE_API_TOKEN}' -d 'email=${CLOUDFLARE_EMAIL}' -d 'z=charlesmilette.net' -d 'v=1'