language: node_js
node_js:
  - "6.2.1"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools

script:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project ${FIREBASE_PROJECT} --only hosting --non-interactive

after_success:
  - sh delete-changed-files.sh