language: node_js

branches:
  only:
    - master

install:
  - npm install -g firebase-tools

script:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project ${FIREBASE_PROJECT} --only hosting --non-interactive
  - ./delete-changed-files.sh