language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

script:
  - jshint public
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project ${FIREBASE_PROJECT} --only hosting --non-interactive
  - ./delete-changed-files.sh